language: node_js
node_js:
  - 14

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed baoth1/udagram-api-feed:v1
  - docker tag udagram-api-user baoth1/udagram-api-user:v1
  - docker tag udagram-frontend baoth1/udagram-frontend:v1
  - docker tag reverseproxy baoth1/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push baoth1/udagram-api-feed:v1
  - docker push baoth1/udagram-api-user:v1
  - docker push baoth1/udagram-frontend:v1
  - docker push baoth1/reverseproxy:v1